# @generated by `cargo run -p codegen` from thrum-core/src/chi.rs — DO NOT EDIT.
#
# Rust is the canonical home of the wire registry. Hand-edit chi.rs;
# the file is regenerated on every cargo build of thrum-core (build.rs).
# Manual regen: `cargo run -p codegen`.

from __future__ import annotations

THRUM_VERSION = "0.7.0"

class Chi:
    """Every wire-known chi value. Adding a new variant bumps the
    protocol minor; renaming/removing bumps major."""
    # announce self — protoVersion, bee, version
    HELLO: str = "hello"
    # start a turn — content, system, tools
    PROMPT: str = "prompt"
    # interrupt mid-turn
    CANCEL: str = "cancel"
    # session deleted, drop daemon state
    CLEANUP: str = "cleanup"
    # manual compaction request
    CURATE: str = "curate"
    # resolve an earlier permission-ask
    RELEASE_PERMIT: str = "release-permit"
    # task subagent answered
    TENDRIL_RESULT: str = "tendril-result"
    # nestler-declared tool answered
    TOOL_RESULT: str = "tool-result"
    # OC message-graph update (graft hint)
    PETAL_CELL: str = "petal-cell"
    # handshake — full state sync on connect
    BREATH: str = "breath"
    # model output partwise (text/reasoning/tool)
    CHUNK: str = "chunk"
    # turn complete — finishReason + usage
    FINISH: str = "finish"
    # turn aborted
    ERROR: str = "error"
    # nest spawned, claude session id known
    SESSION_READY: str = "session-ready"
    # process lifecycle event
    PULSE: str = "pulse"
    # mid-stream permission needed
    PERMISSION_ASK: str = "permission-ask"
    # task subagent dispatch
    TENDRIL_REACH: str = "tendril-reach"
    # nestler-declared tool dispatch
    TOOL_CALL: str = "tool-call"
    # out-of-band metadata for a tool result
    TOOL_META: str = "tool-meta"
    # completed-in-server tool execution — purely informational. Carries the full {callId, name, args, result} pair as one tone. Unlike `ToolCall`/`ToolResult` (which form a two-phase handoff requiring the recipient to execute and reply), `ToolInfo` says "this tool ran upstream, here's everything." Consumers render it without taking action. Used by humd when its native MCP tools run in-process, or when a nestler-tool roundtrip completes successfully and observers want a clean audit event.
    TOOL_INFO: str = "tool-info"
    # delivery ack for a rid
    ECHO: str = "echo"
    # drift timing — measured both ways
    PERF_MARK: str = "perf-mark"
    # structured log forwarding
    LOG: str = "log"
    # drone heartbeat
    DRONE: str = "drone"
    # drone swallow + retry signal
    DRONE_RETROFIT: str = "drone-retrofit"
    # register a peer humd — `{ humd_id: hex, hints: [..] }`
    PEER_ADD: str = "peer-add"
    # drop a peer humd — `{ humd_id: hex }`
    PEER_REMOVE: str = "peer-remove"
    # peer humd asks to observe a sid hosted here — `{ sid, to, from, hearOnly }`. The host records `from` as an observer of `sid`; reply tones for that sid fan out to every observer in addition to the prompt origin.
    ATTACH: str = "attach"
    # peer humd stops observing — `{ sid, to, from }`. The host drops `from` from the observer roster for `sid`.
    DETACH: str = "detach"
    # reconcile WaneTracker after a partition heal — `{ from, snapshot }` where `snapshot` is a map of sigil → wane value. The receiver merges each entry by taking the max of local and remote (wane is a Lamport clock; max is convergent). No reply is required — both sides emit their snapshot on heal, so each is informed exactly once.
    WANE_SYNC: str = "wane-sync"
    # ensemble-wide gossip pub-sub message — `{ topic, payload, from, msg_id }`. Fan-out broadcast above the Transport seam: every PeerConnection is a gossip neighbor. The receiver dedups on `msg_id` (sha256("topic:rid:from:payload")[..16]) using a bounded LRU, dispatches to per-topic subscribers, and re-fans the tone to every OTHER installed peer so the message percolates across the mesh. Distinct from unicast `route` (which targets ONE humd) — gossip is mesh-wide announcements: hum relocation, humd overload, drone alerts.
    GOSSIP_PUBLISH: str = "gossip-publish"
    # Kademlia DHT FIND_NODE query — `{ query_id, target: <Hid hex>, from: <Hid hex> }`. The receiver answers with `kad-find-node-resp` carrying up to K HumdAddrs from its routing table closest in XOR distance to `target`. Sent during `Ensemble::kad_find` iterative lookups when a peer's HumdAddr isn't already known locally.
    KAD_FIND_NODE: str = "kad-find-node"
    # Kademlia DHT FIND_NODE response — `{ query_id, from: <Hid hex>, closest: [<HumdAddr JSON>, ...] }`. Matched to the originating `kad-find-node` by `query_id`. The lookup driver inserts every advertised HumdAddr into its routing table and re-queries the α closest unqueried peers until no closer node is returned.
    KAD_FIND_NODE_RESP: str = "kad-find-node-resp"

ALL_CHI: frozenset[str] = frozenset({
    "hello",
    "prompt",
    "cancel",
    "cleanup",
    "curate",
    "release-permit",
    "tendril-result",
    "tool-result",
    "petal-cell",
    "breath",
    "chunk",
    "finish",
    "error",
    "session-ready",
    "pulse",
    "permission-ask",
    "tendril-reach",
    "tool-call",
    "tool-meta",
    "tool-info",
    "echo",
    "perf-mark",
    "log",
    "drone",
    "drone-retrofit",
    "peer-add",
    "peer-remove",
    "attach",
    "detach",
    "wane-sync",
    "gossip-publish",
    "kad-find-node",
    "kad-find-node-resp",
})

def is_valid_chi(value: str) -> bool:
    return value in ALL_CHI

class PulseKind:
    """pulse.kind enum within chi:'pulse' tones."""
    # process created
    CELL_SPAWNED: str = "cell-spawned"
    # system init received, accepting input
    CELL_READY: str = "cell-ready"
    # turn complete, no listeners
    CELL_IDLE: str = "cell-idle"
    # process exited
    CELL_DIED: str = "cell-died"
    # killed to make room
    CELL_EVICTED: str = "cell-evicted"

