# @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
#
# Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
# so the Python side cannot drift from the Rust side.

from __future__ import annotations

import hashlib
import json
import os
import secrets
import threading
import time
from typing import Any, Mapping


def sigil(sid: str, nest: str) -> str:
    """Deterministic 12-char identity for a (nest, sid) pair.

    Returns lowercase hex of the first 6 sha256 bytes of `nest:sid`.
    Required-`nest`, no fallback — the protocol layer must not know
    about specific nest kinds.
    """
    h = hashlib.sha256(f"{nest}:{sid}".encode("utf-8")).digest()
    return h[:6].hex()


def now_ms() -> int:
    """Wall-clock milliseconds since the Unix epoch."""
    return int(time.time() * 1000)


_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _hum_id_from_bytes(buf: bytes) -> str:
    """Encode 32 bytes (48-bit ms prefix + 208 random bits) as a 52-char
    Crockford base32 id. Mirrors hum_identity's encode bit-for-bit."""
    v = int.from_bytes(buf, "big") << 4
    return "".join(_CROCKFORD[(v >> (255 - 5 * i)) & 0x1F] for i in range(52))


def rid() -> str:
    """Correlation id in canonical HumId form: 52-char Crockford base32,
    ts-prefixed, matching hum_identity::HumId::mint()."""
    ts = int(time.time() * 1000)
    buf = ts.to_bytes(6, "big") + secrets.token_bytes(26)
    return _hum_id_from_bytes(buf)


def is_valid_rid(value: str) -> bool:
    """True iff `value` is a 52-char Crockford base32 id."""
    return (
        len(value) == 52
        and all(c in _CROCKFORD for c in value)
    )


def dusk_in(ms: int) -> int:
    """Absolute ms timestamp at which a tone with this dusk expires."""
    return now_ms() + ms


def is_dusk(tone: Mapping[str, Any]) -> bool:
    """True iff `tone.dusk` is set and already past."""
    d = tone.get("dusk")
    return isinstance(d, (int, float)) and now_ms() > d


class WaneTracker:
    """Lamport clock per sigil. Both sides track their own wane;
    divergence triggers resync via chi:'wane-sync'."""

    def __init__(self) -> None:
        self._counters: dict[str, int] = {}
        self._lock = threading.Lock()

    def get(self, sigil: str) -> int:
        with self._lock:
            return self._counters.get(sigil, 0)

    def tick(self, sigil: str) -> int:
        with self._lock:
            n = self._counters.get(sigil, 0) + 1
            self._counters[sigil] = n
            return n

    def set(self, sigil: str, value: int) -> None:
        with self._lock:
            self._counters[sigil] = value

    def behind(self, sigil: str, remote: int) -> bool:
        with self._lock:
            return remote > self._counters.get(sigil, 0)


def default_socket_path() -> str:
    """Resolve the humd thrum socket:
    HUM_THRUM_SOCK > $XDG_STATE_HOME/hum/runtime.json (rendezvous) > $XDG_STATE_HOME/hum/thrum.sock."""
    explicit = os.environ.get("HUM_THRUM_SOCK")
    if explicit:
        return explicit
    state = os.environ.get("XDG_STATE_HOME") or os.path.join(os.path.expanduser("~"), ".local", "state")
    try:
        with open(os.path.join(state, "hum", "runtime.json"), "r") as f:
            sock = json.load(f).get("socket")
            if sock:
                return sock
    except (OSError, ValueError):
        pass
    return os.path.join(state, "hum", "thrum.sock")
