# @generated by `cargo run -p codegen` from thrum-core/src/views.rs, thrum-core/src/envelope.rs — DO NOT EDIT.
#
# Canonical wire views: every chi body is a Rust struct in
# thrum-core/src/views.rs, the envelope in envelope.rs. These
# client mirrors come out of the same source — no hand-sync.
# Manual regen: `cargo run -p codegen`.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional

@dataclass
class HelloBody:
    proto_version: str
    bee: str
    version: str
    hid: Optional[str] = None
    tool_names: Optional[list[str]] = None
    provides: Optional[list[str]] = None
    source: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "proto_version": "protoVersion",
        "bee": "bee",
        "version": "version",
        "hid": "hid",
        "tool_names": "tool_names",
        "provides": "provides",
        "source": "source",
    }

@dataclass
class PromptBody:
    model_id: Optional[str] = None
    cwd: Optional[str] = None
    system_prompt: Optional[str] = None
    text: Optional[str] = None
    content: Optional[list[Any]] = None
    tools: Optional[list[Any]] = None
    forager_tools: Optional[list[Any]] = None
    provided: Optional[list[str]] = None
    disallowed_tools: Optional[list[str]] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "model_id": "modelId",
        "cwd": "cwd",
        "system_prompt": "systemPrompt",
        "text": "text",
        "content": "content",
        "tools": "tools",
        "forager_tools": "foragerTools",
        "provided": "provided",
        "disallowed_tools": "disallowedTools",
    }

@dataclass
class BreathBody:
    sessions: Any
    proto_version: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "sessions": "sessions",
        "proto_version": "protoVersion",
    }

@dataclass
class ChunkBody:
    chunk_type: str
    block_idx: Optional[int] = None
    delta: Optional[Any] = None
    partial_json: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "chunk_type": "chunkType",
        "block_idx": "blockIdx",
        "delta": "delta",
        "partial_json": "partialJson",
    }

@dataclass
class FinishBody:
    finish_reason: str
    usage: Optional[Any] = None
    exit_code: Optional[int] = None
    subtype: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "finish_reason": "finishReason",
        "usage": "usage",
        "exit_code": "exitCode",
        "subtype": "subtype",
    }

@dataclass
class ErrorBody:
    message: str
    code: Optional[str] = None
    subtype: Optional[str] = None
    usage: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "message": "message",
        "code": "code",
        "subtype": "subtype",
        "usage": "usage",
    }

@dataclass
class SessionReadyBody:
    nest_id: str
    model: str
    tools: Optional[list[Any]] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "nest_id": "nestId",
        "model": "model",
        "tools": "tools",
    }

@dataclass
class ToolCallBody:
    call_id: str
    tool_name: str
    name: Optional[str] = None
    args: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "tool_name": "toolName",
        "name": "name",
        "args": "args",
    }

@dataclass
class ToolResultBody:
    call_id: str
    output: Optional[str] = None
    result: Optional[str] = None
    is_error: Optional[bool] = None
    title: Optional[str] = None
    metadata: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "output": "output",
        "result": "result",
        "is_error": "isError",
        "title": "title",
        "metadata": "metadata",
    }

@dataclass
class ToolInfoBody:
    call_id: str
    name: Optional[str] = None
    args: Optional[Any] = None
    result: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "name": "name",
        "args": "args",
        "result": "result",
    }

@dataclass
class ToolMetaBody:
    call_id: Optional[str] = None
    tool_name: Optional[str] = None
    metadata: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "tool_name": "toolName",
        "metadata": "metadata",
    }

@dataclass
class PulseBody:
    kind: str
    pid: Optional[int] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "kind": "kind",
        "pid": "pid",
    }

@dataclass
class PermissionAskBody:
    call_id: Optional[str] = None
    tool_name: Optional[str] = None
    message: Optional[str] = None
    arg: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "tool_name": "toolName",
        "message": "message",
        "arg": "arg",
    }

@dataclass
class ReleasePermitBody:
    call_id: Optional[str] = None
    ok: Optional[bool] = None
    error: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "ok": "ok",
        "error": "error",
    }

@dataclass
class EchoBody:
    ok: bool
    error: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "ok": "ok",
        "error": "error",
    }

@dataclass
class LogBody:
    level: Optional[str] = None
    message: Optional[str] = None
    fields: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "level": "level",
        "message": "message",
        "fields": "fields",
    }

@dataclass
class DroneBody:
    health: str
    rhythm_ms: Optional[int] = None
    pending_echoes: Optional[list[Any]] = None
    load: Optional[DroneLoad] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "health": "health",
        "rhythm_ms": "rhythm_ms",
        "pending_echoes": "pending_echoes",
        "load": "load",
    }

@dataclass
class DroneLoad:
    active_sigils: Optional[int] = None
    pending_permissions: Optional[int] = None
    inflight_tools: Optional[int] = None
    tokens_burned: Optional[int] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "active_sigils": "active_sigils",
        "pending_permissions": "pending_permissions",
        "inflight_tools": "inflight_tools",
        "tokens_burned": "tokens_burned",
    }

@dataclass
class DroneRetrofitBody:
    sigil: Optional[str] = None
    reason: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "sigil": "sigil",
        "reason": "reason",
    }

@dataclass
class PeerAddBody:
    humd_id: str
    hints: Optional[list[Any]] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "humd_id": "humd_id",
        "hints": "hints",
    }

@dataclass
class PeerRemoveBody:
    humd_id: str

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "humd_id": "humd_id",
    }

@dataclass
class AttachBody:
    hear_only: Optional[bool] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "hear_only": "hearOnly",
    }

@dataclass
class DetachBody:
    pass

@dataclass
class WaneSyncBody:
    snapshot: dict[str, int]

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "snapshot": "snapshot",
    }

@dataclass
class GossipPublishBody:
    topic: str
    payload: Any
    msg_id: str
    from_: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "topic": "topic",
        "payload": "payload",
        "msg_id": "msg_id",
        "from_": "from",
    }

@dataclass
class KadFindNodeBody:
    query_id: str
    target: str

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "query_id": "query_id",
        "target": "target",
    }

@dataclass
class KadFindNodeRespBody:
    query_id: str
    closest: list[Any]

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "query_id": "query_id",
        "closest": "closest",
    }

@dataclass
class BackfillBody:
    author: str
    from_: Optional[int] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "author": "author",
        "from_": "from",
    }

@dataclass
class PerfMarkBody:
    at: Optional[int] = None
    note: Optional[str] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "at": "at",
        "note": "note",
    }

@dataclass
class CancelBody:
    pass

@dataclass
class CleanupBody:
    pass

@dataclass
class CurateBody:
    pass

@dataclass
class TendrilResultBody:
    call_id: Optional[str] = None
    output: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "call_id": "callId",
        "output": "output",
    }

@dataclass
class TendrilReachBody:
    task: Optional[str] = None
    tools: Optional[list[Any]] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "task": "task",
        "tools": "tools",
    }

@dataclass
class PetalCellBody:
    cell: Optional[Any] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "cell": "cell",
    }

@dataclass
class Envelope:
    chi: Chi
    rid: str
    from_: Optional[str] = None
    to: Optional[str] = None
    sigil: Optional[str] = None
    sid: Optional[str] = None
    wane: Optional[int] = None
    sent_at: Optional[int] = None
    dusk: Optional[int] = None
    ext: Optional[dict[str, dict[str, Any]]] = None

    # rust field name -> wire key (single source in views.rs)
    _wire: ClassVar[dict[str, str]] = {
        "chi": "chi",
        "rid": "rid",
        "from_": "from",
        "to": "to",
        "sigil": "sigil",
        "sid": "sid",
        "wane": "wane",
        "sent_at": "sentAt",
        "dusk": "dusk",
        "ext": "ext",
    }

# Serialize a view to the flat wire body (envelope keys not included).
# Absent optionals, like skip_serializing_if on the Rust side, are omitted.
def to_wire(view: Any) -> dict[str, Any]:
    payload: dict[str, Any] = {}
    for rust_name, wire_key in type(view)._wire.items():
        value = getattr(view, rust_name)
        if value is not None:
            payload[wire_key] = value
    return payload

# Parse a flat wire body into the view for `cls`, ignoring envelope
# keys (already stripped) and any unknown keys. Missing required
# fields raise TypeError, surfacing spec drift loudly.
def from_wire(cls: type, payload: dict[str, Any]) -> Any:
    wire_to_rust = {j: f for f, j in cls._wire.items()}
    kwargs = {
        wire_to_rust[k]: v for k, v in payload.items() if k in wire_to_rust
    }
    return cls(**kwargs)

# chi wire value -> body view class.
TONE_VIEWS: dict[str, type] = {
    "hello": HelloBody,
    "prompt": PromptBody,
    "breath": BreathBody,
    "chunk": ChunkBody,
    "finish": FinishBody,
    "error": ErrorBody,
    "session-ready": SessionReadyBody,
    "tool-call": ToolCallBody,
    "tool-result": ToolResultBody,
    "tool-info": ToolInfoBody,
    "tool-meta": ToolMetaBody,
    "pulse": PulseBody,
    "permission-ask": PermissionAskBody,
    "release-permit": ReleasePermitBody,
    "echo": EchoBody,
    "log": LogBody,
    "drone": DroneBody,
    "drone-retrofit": DroneRetrofitBody,
    "peer-add": PeerAddBody,
    "peer-remove": PeerRemoveBody,
    "attach": AttachBody,
    "detach": DetachBody,
    "wane-sync": WaneSyncBody,
    "gossip-publish": GossipPublishBody,
    "kad-find-node": KadFindNodeBody,
    "kad-find-node-resp": KadFindNodeRespBody,
    "backfill": BackfillBody,
    "perf-mark": PerfMarkBody,
    "cancel": CancelBody,
    "cleanup": CleanupBody,
    "curate": CurateBody,
    "tendril-result": TendrilResultBody,
    "tendril-reach": TendrilReachBody,
    "petal-cell": PetalCellBody,
}
