// @generated by `cargo run -p codegen` from thrum-core/src/chi.rs — DO NOT EDIT.
//
// Rust is the canonical home of the wire registry. Hand-edit chi.rs;
// the file is regenerated on every cargo build of thrum-core (build.rs).
// Manual regen: `cargo run -p codegen`.

export const THRUM_VERSION = "0.2.0" as const;

// Every wire-known chi value. Adding a new variant bumps the
// protocol minor; renaming/removing bumps major.
export const Chi = {
  /** announce self — protoVersion, nestling, version */
  hello: "hello",
  /** start a turn — content, system, tools */
  prompt: "prompt",
  /** interrupt mid-turn */
  cancel: "cancel",
  /** session deleted, drop daemon state */
  cleanup: "cleanup",
  /** manual compaction request */
  curate: "curate",
  /** resolve an earlier permission-ask */
  releasePermit: "release-permit",
  /** task subagent answered */
  tendrilResult: "tendril-result",
  /** nestler-declared tool answered */
  toolResult: "tool-result",
  /** OC message-graph update (graft hint) */
  petalCell: "petal-cell",
  /** handshake — full state sync on connect */
  breath: "breath",
  /** model output partwise (text/reasoning/tool) */
  chunk: "chunk",
  /** turn complete — finishReason + usage */
  finish: "finish",
  /** turn aborted */
  error: "error",
  /** nest spawned, claude session id known */
  sessionReady: "session-ready",
  /** process lifecycle event */
  pulse: "pulse",
  /** mid-stream permission needed */
  permissionAsk: "permission-ask",
  /** task subagent dispatch */
  tendrilReach: "tendril-reach",
  /** nestler-declared tool dispatch */
  toolCall: "tool-call",
  /** out-of-band metadata for a tool result */
  toolMeta: "tool-meta",
  /** delivery ack for a rid */
  echo: "echo",
  /** drift timing — measured both ways */
  perfMark: "perf-mark",
  /** structured log forwarding */
  log: "log",
  /** drone heartbeat */
  drone: "drone",
  /** drone swallow + retry signal */
  droneRetrofit: "drone-retrofit",
} as const;
export type ChiKind = typeof Chi[keyof typeof Chi];

export const ALL_CHI: ReadonlySet<ChiKind> = new Set(Object.values(Chi));
export function isValidChi(s: string): s is ChiKind { return ALL_CHI.has(s as ChiKind); }

// pulse.kind is its own enum within chi:"pulse" tones.
export const PulseKind = {
  /** process created */
  roostSpawned: "roost-spawned",
  /** system init received, accepting input */
  roostReady: "roost-ready",
  /** turn complete, no listeners */
  roostIdle: "roost-idle",
  /** process exited */
  roostDied: "roost-died",
  /** killed to make room */
  roostEvicted: "roost-evicted",
} as const;
export type PulseKindT = typeof PulseKind[keyof typeof PulseKind];

// Fields every tone may carry. `chi` and `rid` are required; the rest
// are situational. `ext` is the nestling-private extension bag — thrum
// core ignores it, each nestling owns its own key.
export interface Envelope {
  chi: ChiKind;
  rid: string;
  from?: string;
  to?: string;
  sigil?: string;
  sid?: string;
  wane?: number;
  sentAt?: number;
  dusk?: number;
  ext?: Record<string, Record<string, unknown>>;
}

export type Tone = Envelope & Record<string, unknown>;

export function isEnvelope(x: unknown): x is Envelope {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  return typeof o.chi === "string"
    && (typeof o.rid === "string" || o.rid === undefined)
    && (o.sid === undefined || typeof o.sid === "string");
}

export function isKnownTone(x: unknown): x is Tone {
  return isEnvelope(x) && isValidChi((x as Envelope).chi as string);
}
