// @generated by `cargo run -p codegen` from thrum-core/src/chi.rs — DO NOT EDIT.
//
// Rust is the canonical home of the wire registry. Hand-edit chi.rs;
// regen by running `cargo run -p codegen`. This file ships with the
// TS side so nestlings don't need a build-time Rust toolchain.

export const THRUM_VERSION = "0.2.0" as const;

// Every wire-known chi value. Adding a new variant bumps the
// protocol minor; renaming/removing bumps major.
export const Chi = {
  hello: "hello",
  prompt: "prompt",
  cancel: "cancel",
  cleanup: "cleanup",
  curate: "curate",
  releasePermit: "release-permit",
  tendrilResult: "tendril-result",
  toolResult: "tool-result",
  petalCell: "petal-cell",
  breath: "breath",
  chunk: "chunk",
  finish: "finish",
  error: "error",
  sessionReady: "session-ready",
  pulse: "pulse",
  permissionAsk: "permission-ask",
  tendrilReach: "tendril-reach",
  toolCall: "tool-call",
  toolMeta: "tool-meta",
  echo: "echo",
  perfMark: "perf-mark",
  log: "log",
  drone: "drone",
  droneRetrofit: "drone-retrofit",
} as const;
export type ChiKind = typeof Chi[keyof typeof Chi];

export const ALL_CHI: ReadonlySet<ChiKind> = new Set(Object.values(Chi));
export function isValidChi(s: string): s is ChiKind { return ALL_CHI.has(s as ChiKind); }

// pulse.kind is its own enum within chi:"pulse" tones.
export const PulseKind = {
  roostSpawned: "roost-spawned",
  roostReady: "roost-ready",
  roostIdle: "roost-idle",
  roostDied: "roost-died",
  roostEvicted: "roost-evicted",
} as const;
export type PulseKindT = typeof PulseKind[keyof typeof PulseKind];

// Fields every tone may carry. `chi` and `rid` are required; the rest
// are situational. `ext` is the nestling-private extension bag —
// thrum ignores it, each nestling owns its own key.
export interface Envelope {
  chi: ChiKind;
  rid: string;        // correlation id — required, unique per send
  from?: string;      // sender identity
  to?: string;        // recipient identity (omit = sid-routed or broadcast)
  sigil?: string;     // sentinel pairing hash for this sid
  sid?: string;       // hum session id
  wane?: number;      // sender's wane for this sigil at send time
  sentAt?: number;    // ms timestamp for drift attribution
  dusk?: number;      // absolute expiry; past this, drop tone
  ext?: Record<string, Record<string, unknown>>;
}

export type Tone = Envelope & Record<string, unknown>;

export function isEnvelope(x: unknown): x is Envelope {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  return typeof o.chi === "string"
    && (typeof o.rid === "string" || o.rid === undefined)
    && (o.sid === undefined || typeof o.sid === "string");
}

export function isKnownTone(x: unknown): x is Tone {
  return isEnvelope(x) && isValidChi((x as Envelope).chi as string);
}
