//! Mirror `thrum/chi.ts` into Rust. Tiny CLI; no TS parser, just text scanning.
//!
//! Reads the `Chi` const-object block and the `THRUM_VERSION` literal, emits
//! a Rust source file with the matching enum and version constant. Validates
//! that every camelCase TS key, when serialized as kebab-case from the
//! generated variant, equals its wire value.

use std::fs;
use std::path::PathBuf;

use anyhow::{anyhow, bail, Context, Result};
use regex::Regex;

fn main() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let input = args
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(default_input);
    let output = args
        .next()
        .map(PathBuf::from)
        .unwrap_or_else(default_output);

    let src = fs::read_to_string(&input)
        .with_context(|| format!("read {}", input.display()))?;

    let version = extract_version(&src)?;
    let chi = extract_const_block(&src, "Chi")?;
    let pulse = extract_const_block(&src, "PulseKind")?;

    for (key, wire) in chi.iter().chain(pulse.iter()) {
        let derived = camel_to_kebab(key);
        if derived != *wire {
            bail!(
                "wire mismatch: key `{}` would serialize as `{}` but file says `{}`",
                key, derived, wire
            );
        }
    }

    let out = render_rust(&version, &chi, &pulse);
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(&output, out).with_context(|| format!("write {}", output.display()))?;
    eprintln!("codegen: {} ({} chi, {} pulse) -> {}", version, chi.len(), pulse.len(), output.display());
    Ok(())
}

fn default_input() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../thrum/chi.ts")
}

fn default_output() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../thrum-core/src/generated.rs")
}

fn extract_version(src: &str) -> Result<String> {
    let re = Regex::new(r#"export\s+const\s+THRUM_VERSION\s*=\s*"([^"]+)""#)?;
    let caps = re
        .captures(src)
        .ok_or_else(|| anyhow!("THRUM_VERSION not found"))?;
    Ok(caps[1].to_string())
}

/// Find `export const <name> = {` and collect `key: "value"` pairs until the
/// matching `}`. Tolerates `// comments` and arbitrary whitespace; ignores
/// any line that isn't a key-value pair (e.g. blank or comment-only lines).
fn extract_const_block(src: &str, name: &str) -> Result<Vec<(String, String)>> {
    let opener = Regex::new(&format!(r"export\s+const\s+{}\s*=\s*\{{", regex::escape(name)))?;
    let m = opener
        .find(src)
        .ok_or_else(|| anyhow!("`export const {} = {{` not found", name))?;
    let body_start = m.end();
    // Walk forward tracking brace depth so we stop at the matching `}`.
    let bytes = src.as_bytes();
    let mut depth = 1usize;
    let mut i = body_start;
    while i < bytes.len() && depth > 0 {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    break;
                }
            }
            _ => {}
        }
        i += 1;
    }
    if depth != 0 {
        bail!("unterminated `{}` block", name);
    }
    let body = &src[body_start..i];

    // key:  "value"  — comments after the closing quote are stripped by regex.
    let pair = Regex::new(r#"(?m)^\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*"([^"]+)""#)?;
    let mut out = Vec::new();
    for caps in pair.captures_iter(body) {
        out.push((caps[1].to_string(), caps[2].to_string()));
    }
    if out.is_empty() {
        bail!("`{}` block parsed but yielded no entries", name);
    }
    Ok(out)
}

fn camel_to_kebab(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('-');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn camel_to_pascal(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn render_rust(version: &str, chi: &[(String, String)], pulse: &[(String, String)]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by `cargo run -p codegen` from thrum/chi.ts — DO NOT EDIT.\n");
    s.push_str("//\n");
    s.push_str("// Source of truth lives in TypeScript so the nestlers and the daemon\n");
    s.push_str("// agree on one wire registry. Re-run codegen whenever chi.ts moves.\n\n");
    s.push_str("use serde::{Deserialize, Serialize};\n\n");
    s.push_str(&format!("pub const THRUM_VERSION: &str = \"{}\";\n\n", version));

    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    s.push_str("#[serde(rename_all = \"kebab-case\")]\n");
    s.push_str("pub enum Chi {\n");
    for (key, _wire) in chi {
        s.push_str(&format!("    {},\n", camel_to_pascal(key)));
    }
    s.push_str("}\n\n");

    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    s.push_str("#[serde(rename_all = \"kebab-case\")]\n");
    s.push_str("pub enum PulseKind {\n");
    for (key, _wire) in pulse {
        s.push_str(&format!("    {},\n", camel_to_pascal(key)));
    }
    s.push_str("}\n");

    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kebab() {
        assert_eq!(camel_to_kebab("hello"), "hello");
        assert_eq!(camel_to_kebab("toolCall"), "tool-call");
        assert_eq!(camel_to_kebab("releasePermit"), "release-permit");
        assert_eq!(camel_to_kebab("droneRetrofit"), "drone-retrofit");
    }

    #[test]
    fn pascal() {
        assert_eq!(camel_to_pascal("hello"), "Hello");
        assert_eq!(camel_to_pascal("toolCall"), "ToolCall");
    }
}
