# @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
#
# Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
# so the Python side cannot drift from the Rust side.

from __future__ import annotations

import hashlib
import os
import threading
import time
from typing import Any, Mapping


def sigil(sid: str, nest: str) -> str:
    """Deterministic 12-char identity for a (nest, sid) pair.

    Returns lowercase hex of the first 6 sha256 bytes of `nest:sid`.
    Required-`nest`, no fallback — the protocol layer must not know
    about specific nest kinds.
    """
    h = hashlib.sha256(f"{nest}:{sid}".encode("utf-8")).digest()
    return h[:6].hex()


def now_ms() -> int:
    """Wall-clock milliseconds since the Unix epoch."""
    return int(time.time() * 1000)


_RID_LOCK = threading.Lock()
_RID_COUNTER = 0


def _base36(n: int) -> str:
    if n == 0:
        return "0"
    alphabet = "0123456789abcdefghijklmnopqrstuvwxyz"
    out = []
    while n > 0:
        out.append(alphabet[n % 36])
        n //= 36
    return "".join(reversed(out))


def rid() -> str:
    """Monotonic correlation id: '{base36-ms}-{base36-counter}'."""
    global _RID_COUNTER
    with _RID_LOCK:
        n = _RID_COUNTER
        _RID_COUNTER += 1
    return f"{_base36(now_ms())}-{_base36(n)}"


def dusk_in(ms: int) -> int:
    """Absolute ms timestamp at which a tone with this dusk expires."""
    return now_ms() + ms


def is_dusk(tone: Mapping[str, Any]) -> bool:
    """True iff `tone.dusk` is set and already past."""
    d = tone.get("dusk")
    return isinstance(d, (int, float)) and now_ms() > d


class WaneTracker:
    """Lamport clock per sigil. Both sides track their own wane;
    divergence triggers resync via chi:'wane-sync'."""

    def __init__(self) -> None:
        self._counters: dict[str, int] = {}
        self._lock = threading.Lock()

    def get(self, sigil: str) -> int:
        with self._lock:
            return self._counters.get(sigil, 0)

    def tick(self, sigil: str) -> int:
        with self._lock:
            n = self._counters.get(sigil, 0) + 1
            self._counters[sigil] = n
            return n

    def set(self, sigil: str, value: int) -> None:
        with self._lock:
            self._counters[sigil] = value

    def behind(self, sigil: str, remote: int) -> bool:
        with self._lock:
            return remote > self._counters.get(sigil, 0)


def default_socket_path() -> str:
    """Resolve the humd thrum socket per WIRE.md priority:
    HUM_THRUM_SOCK > $XDG_RUNTIME_DIR/hum/thrum.sock > /run/user/<uid>/hum/thrum.sock."""
    explicit = os.environ.get("HUM_THRUM_SOCK")
    if explicit:
        return explicit
    runtime = os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.geteuid()}"
    return os.path.join(runtime, "hum", "thrum.sock")
