// @generated by `cargo run -p codegen` from thrum/chi.ts — DO NOT EDIT.
//
// Source of truth lives in TypeScript so the nestlers and the daemon
// agree on one wire registry. Re-run codegen whenever chi.ts moves.

use serde::{Deserialize, Serialize};

pub const THRUM_VERSION: &str = "0.2.0";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Chi {
    Hello,
    Prompt,
    Cancel,
    Cleanup,
    Curate,
    ReleasePermit,
    TendrilResult,
    ToolResult,
    PetalCell,
    Breath,
    Chunk,
    Finish,
    Error,
    SessionReady,
    Pulse,
    PermissionAsk,
    TendrilReach,
    ToolCall,
    ToolMeta,
    Echo,
    PerfMark,
    Log,
    Drone,
    DroneRetrofit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PulseKind {
    RoostSpawned,
    RoostReady,
    RoostIdle,
    RoostDied,
    RoostEvicted,
}
