// @generated by `cargo run -p codegen` from thrum-core/src/chi.rs — DO NOT EDIT.
//
// Rust is the canonical home of the wire registry. Hand-edit chi.rs;
// the file is regenerated on every cargo build of thrum-core (build.rs).
// Manual regen: `cargo run -p codegen`.

export const THRUM_VERSION = "0.7.0" as const;

// Every wire-known chi value. Adding a new variant bumps the
// protocol minor; renaming/removing bumps major.
export const Chi = {
  /** announce self — protoVersion, nestling, version */
  hello: "hello",
  /** start a turn — content, system, tools */
  prompt: "prompt",
  /** interrupt mid-turn */
  cancel: "cancel",
  /** session deleted, drop daemon state */
  cleanup: "cleanup",
  /** manual compaction request */
  curate: "curate",
  /** resolve an earlier permission-ask */
  releasePermit: "release-permit",
  /** task subagent answered */
  tendrilResult: "tendril-result",
  /** nestler-declared tool answered */
  toolResult: "tool-result",
  /** OC message-graph update (graft hint) */
  petalCell: "petal-cell",
  /** handshake — full state sync on connect */
  breath: "breath",
  /** model output partwise (text/reasoning/tool) */
  chunk: "chunk",
  /** turn complete — finishReason + usage */
  finish: "finish",
  /** turn aborted */
  error: "error",
  /** nest spawned, claude session id known */
  sessionReady: "session-ready",
  /** process lifecycle event */
  pulse: "pulse",
  /** mid-stream permission needed */
  permissionAsk: "permission-ask",
  /** task subagent dispatch */
  tendrilReach: "tendril-reach",
  /** nestler-declared tool dispatch */
  toolCall: "tool-call",
  /** out-of-band metadata for a tool result */
  toolMeta: "tool-meta",
  /** completed-in-server tool execution — purely informational. Carries the full {callId, name, args, result} pair as one tone. Unlike `ToolCall`/`ToolResult` (which form a two-phase handoff requiring the recipient to execute and reply), `ToolInfo` says "this tool ran upstream, here's everything." Consumers render it without taking action. Used by humd when its native MCP tools run in-process, or when a nestler-tool roundtrip completes successfully and observers want a clean audit event. */
  toolInfo: "tool-info",
  /** delivery ack for a rid */
  echo: "echo",
  /** drift timing — measured both ways */
  perfMark: "perf-mark",
  /** structured log forwarding */
  log: "log",
  /** drone heartbeat */
  drone: "drone",
  /** drone swallow + retry signal */
  droneRetrofit: "drone-retrofit",
  /** register a peer humd — `{ humd_id: hex, hints: [..] }` */
  peerAdd: "peer-add",
  /** drop a peer humd — `{ humd_id: hex }` */
  peerRemove: "peer-remove",
  /** peer humd asks to observe a sid hosted here — `{ sid, to, from, hearOnly }`. The host records `from` as an observer of `sid`; reply tones for that sid fan out to every observer in addition to the prompt origin. */
  attach: "attach",
  /** peer humd stops observing — `{ sid, to, from }`. The host drops `from` from the observer roster for `sid`. */
  detach: "detach",
  /** reconcile WaneTracker after a partition heal — `{ from, snapshot }` where `snapshot` is a map of sigil → wane value. The receiver merges each entry by taking the max of local and remote (wane is a Lamport clock; max is convergent). No reply is required — both sides emit their snapshot on heal, so each is informed exactly once. */
  waneSync: "wane-sync",
  /** ensemble-wide gossip pub-sub message — `{ topic, payload, from, msg_id }`. Fan-out broadcast above the Transport seam: every PeerConnection is a gossip neighbor. The receiver dedups on `msg_id` (sha256("topic:rid:from:payload")[..16]) using a bounded LRU, dispatches to per-topic subscribers, and re-fans the tone to every OTHER installed peer so the message percolates across the mesh. Distinct from unicast `route` (which targets ONE humd) — gossip is mesh-wide announcements: hum relocation, humd overload, drone alerts. */
  gossipPublish: "gossip-publish",
  /** Kademlia DHT FIND_NODE query — `{ query_id, target: <HumdId hex>, from: <HumdId hex> }`. The receiver answers with `kad-find-node-resp` carrying up to K HumdAddrs from its routing table closest in XOR distance to `target`. Sent during `Ensemble::kad_find` iterative lookups when a peer's HumdAddr isn't already known locally. */
  kadFindNode: "kad-find-node",
  /** Kademlia DHT FIND_NODE response — `{ query_id, from: <HumdId hex>, closest: [<HumdAddr JSON>, ...] }`. Matched to the originating `kad-find-node` by `query_id`. The lookup driver inserts every advertised HumdAddr into its routing table and re-queries the α closest unqueried peers until no closer node is returned. */
  kadFindNodeResp: "kad-find-node-resp",
} as const;
export type ChiKind = typeof Chi[keyof typeof Chi];

export const ALL_CHI: ReadonlySet<ChiKind> = new Set(Object.values(Chi));
export function isValidChi(s: string): s is ChiKind { return ALL_CHI.has(s as ChiKind); }

// pulse.kind is its own enum within chi:"pulse" tones.
export const PulseKind = {
  /** process created */
  roostSpawned: "roost-spawned",
  /** system init received, accepting input */
  roostReady: "roost-ready",
  /** turn complete, no listeners */
  roostIdle: "roost-idle",
  /** process exited */
  roostDied: "roost-died",
  /** killed to make room */
  roostEvicted: "roost-evicted",
} as const;
export type PulseKindT = typeof PulseKind[keyof typeof PulseKind];

// Fields every tone may carry. `chi` and `rid` are required; the rest
// are situational. `ext` is the nestling-private extension bag — thrum
// core ignores it, each nestling owns its own key.
export interface Envelope {
  chi: ChiKind;
  rid: string;
  from?: string;
  to?: string;
  sigil?: string;
  sid?: string;
  wane?: number;
  sentAt?: number;
  dusk?: number;
  ext?: Record<string, Record<string, unknown>>;
}

export type Tone = Envelope & Record<string, unknown>;

export function isEnvelope(x: unknown): x is Envelope {
  if (!x || typeof x !== "object") return false;
  const o = x as Record<string, unknown>;
  return typeof o.chi === "string"
    && (typeof o.rid === "string" || o.rid === undefined)
    && (o.sid === undefined || typeof o.sid === "string");
}

export function isKnownTone(x: unknown): x is Tone {
  return isEnvelope(x) && isValidChi((x as Envelope).chi as string);
}
