// @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
//
// Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
// so the TS side cannot drift from the Rust side. If you need a new
// helper, add it in Rust first and extend codegen's render_helpers.

import { createHash } from "crypto";

/**
 * Deterministic identity for a (nest, session) pair.
 *
 * `nest` is the nest-kind namespace — "claude-cli", "claude-repl", or
 * any other future nest implementation. Required; no default — the
 * protocol layer must not know about specific kinds.
 *
 * Returns the lowercase hex of the first 6 sha256 bytes (12 chars).
 */
export function sigil(sid: string, nest: string): string {
  return createHash("sha256")
    .update(`${nest}:${sid}`)
    .digest("hex")
    .slice(0, 12);
}

/** Monotonic request id — base36 timestamp + counter. */
let __ridCounter = 0;
export function rid(): string {
  return `${Date.now().toString(36)}-${(__ridCounter++).toString(36)}`;
}

/** Absolute ms timestamp ms in the future. */
export function duskIn(ms: number): number {
  return Date.now() + ms;
}

/** True iff `tone.dusk` is set and already past. */
export function isDusk(tone: { dusk?: number }): boolean {
  return typeof tone.dusk === "number" && Date.now() > tone.dusk;
}

/**
 * Drift detection. Monotonic counter per sigil. Both sides track their
 * own wane; when wanes diverge, drift is visible — the stale side
 * resyncs. Mirrors thrum_core::WaneTracker.
 */
export class WaneTracker {
  private counters = new Map<string, number>();
  get(s: string): number { return this.counters.get(s) ?? 0; }
  tick(s: string): number {
    const next = (this.counters.get(s) ?? 0) + 1;
    this.counters.set(s, next);
    return next;
  }
  set(s: string, value: number): void { this.counters.set(s, value); }
  behind(s: string, remote: number): boolean { return remote > this.get(s); }
}
