// @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
//
// Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
// so the TS side cannot drift from the Rust side. If you need a new
// helper, add it in Rust first and extend codegen's render_helpers.

import { createHash, randomBytes } from "crypto";

/**
 * Deterministic identity for a (nest, session) pair.
 *
 * `nest` is the nest-kind namespace — "claude-cli", "claude-repl", or
 * any other future nest implementation. Required; no default — the
 * protocol layer must not know about specific kinds.
 *
 * Returns the lowercase hex of the first 6 sha256 bytes (12 chars).
 */
export function sigil(sid: string, nest: string): string {
  return createHash("sha256")
    .update(`${nest}:${sid}`)
    .digest("hex")
    .slice(0, 12);
}

const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/**
 * Encode 32 bytes (48-bit ms prefix + 208 random bits, big-endian) as a
 * 52-char Crockford base32 id. Mirrors hum_identity's encode bit-for-bit.
 */
export function humIdEncode(buf: Uint8Array): string {
  let v = 0n;
  for (const b of buf) v = (v << 8n) | BigInt(b);
  v <<= 4n;
  let out = "";
  for (let i = 0; i < 52; i++) {
    out += CROCKFORD[Number((v >> BigInt(255 - 5 * i)) & 0x1fn)];
  }
  return out;
}

/**
 * Correlation id in canonical HumId form — 52-char Crockford base32,
 * ts-prefixed, matching hum_identity::HumId::mint().
 */
export function rid(): string {
  const buf = new Uint8Array(32);
  let ms = BigInt(Date.now());
  for (let i = 0; i < 6; i++) {
    buf[5 - i] = Number(ms & 0xffn);
    ms >>= 8n;
  }
  buf.set(randomBytes(26), 6);
  return humIdEncode(buf);
}

/** True iff `value` is a 52-char Crockford base32 id. */
export function isValidRid(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.length === 52 &&
    [...value].every((c) => CROCKFORD.includes(c))
  );
}

/** Absolute ms timestamp ms in the future. */
export function duskIn(ms: number): number {
  return Date.now() + ms;
}

/** True iff `tone.dusk` is set and already past. */
export function isDusk(tone: { dusk?: number }): boolean {
  return typeof tone.dusk === "number" && Date.now() > tone.dusk;
}

/**
 * Drift detection. Monotonic counter per sigil. Both sides track their
 * own wane; when wanes diverge, drift is visible — the stale side
 * resyncs. Mirrors thrum_core::WaneTracker.
 */
export class WaneTracker {
  private counters = new Map<string, number>();
  get(s: string): number { return this.counters.get(s) ?? 0; }
  tick(s: string): number {
    const next = (this.counters.get(s) ?? 0) + 1;
    this.counters.set(s, next);
    return next;
  }
  set(s: string, value: number): void { this.counters.set(s, value); }
  behind(s: string, remote: number): boolean { return remote > this.get(s); }
}
