// @generated by `cargo run -p codegen` from thrum-core/src/views.rs, thrum-core/src/envelope.rs — DO NOT EDIT.
//
// Canonical wire views: every chi body is a Rust struct in
// thrum-core/src/views.rs, the envelope in envelope.rs. These
// client mirrors come out of the same source — no hand-sync.
// Manual regen: `cargo run -p codegen`.

export type { ChiKind } from "./chi.ts";
import type { Chi } from "./chi.ts";

export interface HelloBody {
  protoVersion: string;
  bee: string;
  version: string;
  hid?: string;
  tool_names?: string[];
  provides?: string[];
  source?: string;
}

export interface PromptBody {
  modelId?: string;
  cwd?: string;
  systemPrompt?: string;
  text?: string;
  content?: unknown[];
  tools?: unknown[];
  foragerTools?: unknown[];
  provided?: string[];
  disallowedTools?: string[];
}

export interface BreathBody {
  sessions: unknown;
  protoVersion?: string;
}

export interface ChunkBody {
  chunkType: string;
  blockIdx?: number;
  delta?: unknown;
  partialJson?: string;
}

export interface FinishBody {
  finishReason: string;
  usage?: unknown;
  exitCode?: number;
  subtype?: string;
}

export interface ErrorBody {
  message: string;
  code?: string;
  subtype?: string;
  usage?: unknown;
}

export interface SessionReadyBody {
  nestId: string;
  model: string;
  tools?: unknown[];
}

export interface ToolCallBody {
  callId: string;
  toolName: string;
  name?: string;
  args?: unknown;
}

export interface ToolResultBody {
  callId: string;
  output?: string;
  result?: string;
  isError?: boolean;
  title?: string;
  metadata?: unknown;
}

export interface ToolInfoBody {
  callId: string;
  name?: string;
  args?: unknown;
  result?: unknown;
}

export interface ToolMetaBody {
  callId?: string;
  toolName?: string;
  metadata?: unknown;
}

export interface PulseBody {
  kind: string;
  pid?: number;
}

export interface PermissionAskBody {
  callId?: string;
  toolName?: string;
  message?: string;
  arg?: unknown;
}

export interface ReleasePermitBody {
  callId?: string;
  ok?: boolean;
  error?: string;
}

export interface EchoBody {
  ok: boolean;
  error?: string;
}

export interface LogBody {
  level?: string;
  message?: string;
  fields?: unknown;
}

export interface DroneBody {
  health: string;
  rhythm_ms?: number;
  pending_echoes?: unknown[];
  load?: DroneLoad;
}

export interface DroneLoad {
  active_sigils?: number;
  pending_permissions?: number;
  inflight_tools?: number;
  tokens_burned?: number;
}

export interface DroneRetrofitBody {
  sigil?: string;
  reason?: string;
}

export interface PeerAddBody {
  humd_id: string;
  hints?: unknown[];
}

export interface PeerRemoveBody {
  humd_id: string;
}

export interface AttachBody {
  hearOnly?: boolean;
}

export interface DetachBody {
}

export interface WaneSyncBody {
  snapshot: Record<string, number>;
}

export interface GossipPublishBody {
  topic: string;
  payload: unknown;
  from?: string;
  msg_id: string;
}

export interface KadFindNodeBody {
  query_id: string;
  target: string;
}

export interface KadFindNodeRespBody {
  query_id: string;
  closest: unknown[];
}

export interface BackfillBody {
  author: string;
  from?: number;
}

export interface PerfMarkBody {
  at?: number;
  note?: string;
}

export interface CancelBody {
}

export interface CleanupBody {
}

export interface CurateBody {
}

export interface TendrilResultBody {
  callId?: string;
  output?: unknown;
}

export interface TendrilReachBody {
  task?: string;
  tools?: unknown[];
}

export interface PetalCellBody {
  cell?: unknown;
}

export interface Envelope {
  chi: Chi;
  rid: string;
  from?: string;
  to?: string;
  sigil?: string;
  sid?: string;
  wane?: number;
  sentAt?: number;
  dusk?: number;
  ext?: Record<string, Record<string, unknown>>;
}

// Body view per chi wire value.
export interface ToneViews {
  "hello": HelloBody;
  "prompt": PromptBody;
  "breath": BreathBody;
  "chunk": ChunkBody;
  "finish": FinishBody;
  "error": ErrorBody;
  "session-ready": SessionReadyBody;
  "tool-call": ToolCallBody;
  "tool-result": ToolResultBody;
  "tool-info": ToolInfoBody;
  "tool-meta": ToolMetaBody;
  "pulse": PulseBody;
  "permission-ask": PermissionAskBody;
  "release-permit": ReleasePermitBody;
  "echo": EchoBody;
  "log": LogBody;
  "drone": DroneBody;
  "drone-retrofit": DroneRetrofitBody;
  "peer-add": PeerAddBody;
  "peer-remove": PeerRemoveBody;
  "attach": AttachBody;
  "detach": DetachBody;
  "wane-sync": WaneSyncBody;
  "gossip-publish": GossipPublishBody;
  "kad-find-node": KadFindNodeBody;
  "kad-find-node-resp": KadFindNodeRespBody;
  "backfill": BackfillBody;
  "perf-mark": PerfMarkBody;
  "cancel": CancelBody;
  "cleanup": CleanupBody;
  "curate": CurateBody;
  "tendril-result": TendrilResultBody;
  "tendril-reach": TendrilReachBody;
  "petal-cell": PetalCellBody;
}

export type ToneView<C extends keyof ToneViews> = Envelope & ToneViews[C];
