// @generated by `cargo run -p codegen` from thrum-core/src/chi.rs — DO NOT EDIT.
//
// Rust is the canonical home of the wire registry. Hand-edit chi.rs;
// the file is regenerated on every cargo build of thrum-core (build.rs).
// Manual regen: `cargo run -p codegen`.

package thrum

const ThrumVersion = "0.7.0"

// Chi is the discriminator on every tone.
type Chi string

// Every wire-known chi value. Adding a new variant bumps the
// protocol minor; renaming/removing bumps major.
const (
    // announce self — protoVersion, bee, version
    ChiHello Chi = "hello"
    // start a turn — content, system, tools
    ChiPrompt Chi = "prompt"
    // interrupt mid-turn
    ChiCancel Chi = "cancel"
    // session deleted, drop daemon state
    ChiCleanup Chi = "cleanup"
    // manual compaction request
    ChiCurate Chi = "curate"
    // resolve an earlier permission-ask
    ChiReleasePermit Chi = "release-permit"
    // task subagent answered
    ChiTendrilResult Chi = "tendril-result"
    // nestler-declared tool answered
    ChiToolResult Chi = "tool-result"
    // OC message-graph update (graft hint)
    ChiPetalCell Chi = "petal-cell"
    // handshake — full state sync on connect
    ChiBreath Chi = "breath"
    // model output partwise (text/reasoning/tool)
    ChiChunk Chi = "chunk"
    // turn complete — finishReason + usage
    ChiFinish Chi = "finish"
    // turn aborted
    ChiError Chi = "error"
    // nest spawned, claude session id known
    ChiSessionReady Chi = "session-ready"
    // process lifecycle event
    ChiPulse Chi = "pulse"
    // mid-stream permission needed
    ChiPermissionAsk Chi = "permission-ask"
    // task subagent dispatch
    ChiTendrilReach Chi = "tendril-reach"
    // nestler-declared tool dispatch
    ChiToolCall Chi = "tool-call"
    // out-of-band metadata for a tool result
    ChiToolMeta Chi = "tool-meta"
    // completed-in-server tool execution — purely informational. Carries the full {callId, name, args, result} pair as one tone. Unlike `ToolCall`/`ToolResult` (which form a two-phase handoff requiring the recipient to execute and reply), `ToolInfo` says "this tool ran upstream, here's everything." Consumers render it without taking action. Used by humd when its native MCP tools run in-process, or when a nestler-tool roundtrip completes successfully and observers want a clean audit event.
    ChiToolInfo Chi = "tool-info"
    // delivery ack for a rid
    ChiEcho Chi = "echo"
    // drift timing — measured both ways
    ChiPerfMark Chi = "perf-mark"
    // structured log forwarding
    ChiLog Chi = "log"
    // drone heartbeat
    ChiDrone Chi = "drone"
    // drone swallow + retry signal
    ChiDroneRetrofit Chi = "drone-retrofit"
    // register a peer humd — `{ humd_id: hex, hints: [..] }`
    ChiPeerAdd Chi = "peer-add"
    // drop a peer humd — `{ humd_id: hex }`
    ChiPeerRemove Chi = "peer-remove"
    // peer humd asks to observe a sid hosted here — `{ sid, to, from, hearOnly }`. The host records `from` as an observer of `sid`; reply tones for that sid fan out to every observer in addition to the prompt origin.
    ChiAttach Chi = "attach"
    // peer humd stops observing — `{ sid, to, from }`. The host drops `from` from the observer roster for `sid`.
    ChiDetach Chi = "detach"
    // reconcile WaneTracker after a partition heal — `{ from, snapshot }` where `snapshot` is a map of sigil → wane value. The receiver merges each entry by taking the max of local and remote (wane is a Lamport clock; max is convergent). No reply is required — both sides emit their snapshot on heal, so each is informed exactly once.
    ChiWaneSync Chi = "wane-sync"
    // ensemble-wide gossip pub-sub message — `{ topic, payload, from, msg_id }`. Fan-out broadcast above the Transport seam: every PeerConnection is a gossip neighbor. The receiver dedups on `msg_id` (sha256("topic:rid:from:payload")[..16]) using a bounded LRU, dispatches to per-topic subscribers, and re-fans the tone to every OTHER installed peer so the message percolates across the mesh. Distinct from unicast `route` (which targets ONE humd) — gossip is mesh-wide announcements: hum relocation, humd overload, drone alerts.
    ChiGossipPublish Chi = "gossip-publish"
    // Kademlia DHT FIND_NODE query — `{ query_id, target: <HumdId hex>, from: <HumdId hex> }`. The receiver answers with `kad-find-node-resp` carrying up to K HumdAddrs from its routing table closest in XOR distance to `target`. Sent during `Ensemble::kad_find` iterative lookups when a peer's HumdAddr isn't already known locally.
    ChiKadFindNode Chi = "kad-find-node"
    // Kademlia DHT FIND_NODE response — `{ query_id, from: <HumdId hex>, closest: [<HumdAddr JSON>, ...] }`. Matched to the originating `kad-find-node` by `query_id`. The lookup driver inserts every advertised HumdAddr into its routing table and re-queries the α closest unqueried peers until no closer node is returned.
    ChiKadFindNodeResp Chi = "kad-find-node-resp"
)

// AllChi is the set of every known chi value for membership checks.
var AllChi = map[Chi]struct{}{
    ChiHello: {},
    ChiPrompt: {},
    ChiCancel: {},
    ChiCleanup: {},
    ChiCurate: {},
    ChiReleasePermit: {},
    ChiTendrilResult: {},
    ChiToolResult: {},
    ChiPetalCell: {},
    ChiBreath: {},
    ChiChunk: {},
    ChiFinish: {},
    ChiError: {},
    ChiSessionReady: {},
    ChiPulse: {},
    ChiPermissionAsk: {},
    ChiTendrilReach: {},
    ChiToolCall: {},
    ChiToolMeta: {},
    ChiToolInfo: {},
    ChiEcho: {},
    ChiPerfMark: {},
    ChiLog: {},
    ChiDrone: {},
    ChiDroneRetrofit: {},
    ChiPeerAdd: {},
    ChiPeerRemove: {},
    ChiAttach: {},
    ChiDetach: {},
    ChiWaneSync: {},
    ChiGossipPublish: {},
    ChiKadFindNode: {},
    ChiKadFindNodeResp: {},
}

// IsValidChi returns true if value is a known chi.
func IsValidChi(value string) bool {
    _, ok := AllChi[Chi(value)]
    return ok
}

// PulseKind is the kind field within chi:"pulse" tones.
type PulseKind string

const (
    // process created
    PulseKindRoostSpawned PulseKind = "roost-spawned"
    // system init received, accepting input
    PulseKindRoostReady PulseKind = "roost-ready"
    // turn complete, no listeners
    PulseKindRoostIdle PulseKind = "roost-idle"
    // process exited
    PulseKindRoostDied PulseKind = "roost-died"
    // killed to make room
    PulseKindRoostEvicted PulseKind = "roost-evicted"
)
