// @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
//
// Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
// so the Go side cannot drift from the Rust side.

package thrum

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// Sigil returns the 12-char content-addressable identifier for a
// (nest, sid) pair: lowercase hex of the first 6 sha256 bytes of
// "nest:sid". Stable across reconnects.
func Sigil(sid, nest string) string {
	h := sha256.Sum256([]byte(nest + ":" + sid))
	return hex.EncodeToString(h[:6])
}

// NowMs returns wall-clock milliseconds since the Unix epoch.
func NowMs() int64 { return time.Now().UnixMilli() }

const crockford = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

// HumIdEncode encodes 32 bytes (48-bit ms prefix + 208 random bits,
// big-endian) as a 52-char Crockford base32 id. Mirrors hum_identity's
// encode bit-for-bit.
func HumIdEncode(buf [32]byte) string {
	var v big.Int
	v.SetBytes(buf[:])
	v.Lsh(&v, 4)
	var out strings.Builder
	out.Grow(52)
	for i := 0; i < 52; i++ {
		var idx big.Int
		idx.Rsh(&v, uint(255-5*i))
		idx.And(&idx, big.NewInt(0x1f))
		out.WriteByte(crockford[idx.Int64()])
	}
	return out.String()
}

// Rid mints a correlation id in canonical HumId form — 52-char
// Crockford base32, ts-prefixed, matching hum_identity::HumId::mint().
func Rid() string {
	var buf [32]byte
	ms := uint64(NowMs())
	for i := 0; i < 6; i++ {
		buf[5-i] = byte(ms >> (8 * uint(i)))
	}
	if _, err := rand.Read(buf[6:]); err != nil {
		// 26 bytes from the CSPRNG is practically infallible; fall
		// back to a time-seeded value rather than mint nothing.
		buf[6] = byte(ms >> 40)
	}
	return HumIdEncode(buf)
}

// IsValidRid reports whether value is a 52-char Crockford base32 id.
func IsValidRid(value string) bool {
	if len(value) != 52 {
		return false
	}
	for i := 0; i < len(value); i++ {
		if !strings.ContainsRune(crockford, rune(value[i])) {
			return false
		}
	}
	return true
}

// DuskIn returns the absolute ms timestamp at which a tone with this
// dusk expires.
func DuskIn(ms int64) int64 { return NowMs() + ms }

// Tone is the loose-JSON envelope every chi rides inside.
type Tone map[string]any

// IsDusk reports whether tone.dusk is set and already past.
func IsDusk(t Tone) bool {
	switch d := t["dusk"].(type) {
	case float64:
		return NowMs() > int64(d)
	case int64:
		return NowMs() > d
	case int:
		return NowMs() > int64(d)
	}
	return false
}

// WaneTracker is one Lamport clock per sigil. Both sides track their
// own wane; divergence triggers resync via chi:"wane-sync".
type WaneTracker struct {
	mu       sync.Mutex
	counters map[string]int64
}

func NewWaneTracker() *WaneTracker {
	return &WaneTracker{counters: make(map[string]int64)}
}

func (w *WaneTracker) Get(sigil string) int64 {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.counters[sigil]
}

func (w *WaneTracker) Tick(sigil string) int64 {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.counters[sigil]++
	return w.counters[sigil]
}

func (w *WaneTracker) Set(sigil string, value int64) {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.counters[sigil] = value
}

func (w *WaneTracker) Behind(sigil string, remote int64) bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	return remote > w.counters[sigil]
}

// DefaultSocketPath resolves the humd thrum socket:
// HUM_THRUM_SOCK > $XDG_STATE_HOME/hum/runtime.json (rendezvous) > $XDG_STATE_HOME/hum/thrum.sock.
func DefaultSocketPath() string {
	if explicit := os.Getenv("HUM_THRUM_SOCK"); explicit != "" {
		return explicit
	}
	state := os.Getenv("XDG_STATE_HOME")
	if state == "" {
		home, _ := os.UserHomeDir()
		state = filepath.Join(home, ".local", "state")
	}
	if data, err := os.ReadFile(filepath.Join(state, "hum", "runtime.json")); err == nil {
		var rt struct {
			Socket string `json:"socket"`
		}
		if json.Unmarshal(data, &rt) == nil && rt.Socket != "" {
			return rt.Socket
		}
	}
	return filepath.Join(state, "hum", "thrum.sock")
}
