// @generated by `cargo run -p codegen` from thrum-core — DO NOT EDIT.
//
// Runtime helpers that mirror thrum-core/src/{prims,wane}.rs. Generated
// so the Go side cannot drift from the Rust side.

package thrum

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"sync"
	"sync/atomic"
	"time"
)

// Sigil returns the 12-char content-addressable identifier for a
// (nest, sid) pair: lowercase hex of the first 6 sha256 bytes of
// "nest:sid". Stable across reconnects.
func Sigil(sid, nest string) string {
	h := sha256.Sum256([]byte(nest + ":" + sid))
	return hex.EncodeToString(h[:6])
}

// NowMs returns wall-clock milliseconds since the Unix epoch.
func NowMs() int64 { return time.Now().UnixMilli() }

var ridCounter uint64

func base36(n uint64) string {
	if n == 0 {
		return "0"
	}
	return strconv.FormatUint(n, 36)
}

// Rid mints a monotonic correlation id: "{base36-ms}-{base36-counter}".
func Rid() string {
	n := atomic.AddUint64(&ridCounter, 1) - 1
	return fmt.Sprintf("%s-%s", base36(uint64(NowMs())), base36(n))
}

// DuskIn returns the absolute ms timestamp at which a tone with this
// dusk expires.
func DuskIn(ms int64) int64 { return NowMs() + ms }

// Tone is the loose-JSON envelope every chi rides inside.
type Tone map[string]any

// IsDusk reports whether tone.dusk is set and already past.
func IsDusk(t Tone) bool {
	switch d := t["dusk"].(type) {
	case float64:
		return NowMs() > int64(d)
	case int64:
		return NowMs() > d
	case int:
		return NowMs() > int64(d)
	}
	return false
}

// WaneTracker is one Lamport clock per sigil. Both sides track their
// own wane; divergence triggers resync via chi:"wane-sync".
type WaneTracker struct {
	mu       sync.Mutex
	counters map[string]int64
}

func NewWaneTracker() *WaneTracker {
	return &WaneTracker{counters: make(map[string]int64)}
}

func (w *WaneTracker) Get(sigil string) int64 {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.counters[sigil]
}

func (w *WaneTracker) Tick(sigil string) int64 {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.counters[sigil]++
	return w.counters[sigil]
}

func (w *WaneTracker) Set(sigil string, value int64) {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.counters[sigil] = value
}

func (w *WaneTracker) Behind(sigil string, remote int64) bool {
	w.mu.Lock()
	defer w.mu.Unlock()
	return remote > w.counters[sigil]
}

// DefaultSocketPath resolves the humd thrum socket per WIRE.md priority:
// HUM_THRUM_SOCK > $XDG_STATE_HOME/hum/thrum.sock > ~/.local/state/hum/thrum.sock.
func DefaultSocketPath() string {
	if explicit := os.Getenv("HUM_THRUM_SOCK"); explicit != "" {
		return explicit
	}
	state := os.Getenv("XDG_STATE_HOME")
	if state == "" {
		home, _ := os.UserHomeDir()
		state = filepath.Join(home, ".local", "state")
	}
	return filepath.Join(state, "hum", "thrum.sock")
}
