// @generated by `cargo run -p codegen` from thrum-core/src/views.rs, thrum-core/src/envelope.rs — DO NOT EDIT.
//
// Canonical wire views: every chi body is a Rust struct in
// thrum-core/src/views.rs, the envelope in envelope.rs. These
// client mirrors come out of the same source — no hand-sync.
// Manual regen: `cargo run -p codegen`.

package thrum

import "encoding/json"

type HelloBody struct {
	ProtoVersion string `json:"protoVersion"`
	Bee string `json:"bee"`
	Version string `json:"version"`
	Hid *string `json:"hid,omitempty"`
	ToolNames []string `json:"tool_names,omitempty"`
	Provides []string `json:"provides,omitempty"`
	Source *string `json:"source,omitempty"`
}

type PromptBody struct {
	ModelId *string `json:"modelId,omitempty"`
	Cwd *string `json:"cwd,omitempty"`
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	Text *string `json:"text,omitempty"`
	Content []json.RawMessage `json:"content,omitempty"`
	Tools []json.RawMessage `json:"tools,omitempty"`
	ForagerTools []json.RawMessage `json:"foragerTools,omitempty"`
	Provided []string `json:"provided,omitempty"`
	DisallowedTools []string `json:"disallowedTools,omitempty"`
}

type BreathBody struct {
	Sessions json.RawMessage `json:"sessions"`
	ProtoVersion *string `json:"protoVersion,omitempty"`
}

type ChunkBody struct {
	ChunkType string `json:"chunkType"`
	BlockIdx *uint64 `json:"blockIdx,omitempty"`
	Delta json.RawMessage `json:"delta,omitempty"`
	PartialJson *string `json:"partialJson,omitempty"`
}

type FinishBody struct {
	FinishReason string `json:"finishReason"`
	Usage json.RawMessage `json:"usage,omitempty"`
	ExitCode *int64 `json:"exitCode,omitempty"`
	Subtype *string `json:"subtype,omitempty"`
}

type ErrorBody struct {
	Message string `json:"message"`
	Code *string `json:"code,omitempty"`
	Subtype *string `json:"subtype,omitempty"`
	Usage json.RawMessage `json:"usage,omitempty"`
}

type SessionReadyBody struct {
	NestId string `json:"nestId"`
	Model string `json:"model"`
	Tools []json.RawMessage `json:"tools,omitempty"`
}

type ToolCallBody struct {
	CallId string `json:"callId"`
	ToolName string `json:"toolName"`
	Name *string `json:"name,omitempty"`
	Args json.RawMessage `json:"args,omitempty"`
}

type ToolResultBody struct {
	CallId string `json:"callId"`
	Output *string `json:"output,omitempty"`
	Result *string `json:"result,omitempty"`
	IsError *bool `json:"isError,omitempty"`
	Title *string `json:"title,omitempty"`
	Metadata json.RawMessage `json:"metadata,omitempty"`
}

type ToolInfoBody struct {
	CallId string `json:"callId"`
	Name *string `json:"name,omitempty"`
	Args json.RawMessage `json:"args,omitempty"`
	Result json.RawMessage `json:"result,omitempty"`
}

type ToolMetaBody struct {
	CallId *string `json:"callId,omitempty"`
	ToolName *string `json:"toolName,omitempty"`
	Metadata json.RawMessage `json:"metadata,omitempty"`
}

type PulseBody struct {
	Kind string `json:"kind"`
	Pid *int64 `json:"pid,omitempty"`
}

type PermissionAskBody struct {
	CallId *string `json:"callId,omitempty"`
	ToolName *string `json:"toolName,omitempty"`
	Message *string `json:"message,omitempty"`
	Arg json.RawMessage `json:"arg,omitempty"`
}

type ReleasePermitBody struct {
	CallId *string `json:"callId,omitempty"`
	Ok *bool `json:"ok,omitempty"`
	Error *string `json:"error,omitempty"`
}

type EchoBody struct {
	Ok bool `json:"ok"`
	Error *string `json:"error,omitempty"`
}

type LogBody struct {
	Level *string `json:"level,omitempty"`
	Message *string `json:"message,omitempty"`
	Fields json.RawMessage `json:"fields,omitempty"`
}

type DroneBody struct {
	Health string `json:"health"`
	RhythmMs *uint64 `json:"rhythm_ms,omitempty"`
	PendingEchoes []json.RawMessage `json:"pending_echoes,omitempty"`
	Load *DroneLoad `json:"load,omitempty"`
}

type DroneLoad struct {
	ActiveSigils *uint64 `json:"active_sigils,omitempty"`
	PendingPermissions *uint64 `json:"pending_permissions,omitempty"`
	InflightTools *uint64 `json:"inflight_tools,omitempty"`
	TokensBurned *uint64 `json:"tokens_burned,omitempty"`
}

type DroneRetrofitBody struct {
	Sigil *string `json:"sigil,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

type PeerAddBody struct {
	HumdId string `json:"humd_id"`
	Hints []json.RawMessage `json:"hints,omitempty"`
}

type PeerRemoveBody struct {
	HumdId string `json:"humd_id"`
}

type AttachBody struct {
	HearOnly *bool `json:"hearOnly,omitempty"`
}

type DetachBody struct {
}

type WaneSyncBody struct {
	Snapshot map[string]uint64 `json:"snapshot"`
}

type GossipPublishBody struct {
	Topic string `json:"topic"`
	Payload json.RawMessage `json:"payload"`
	From *string `json:"from,omitempty"`
	MsgId string `json:"msg_id"`
}

type KadFindNodeBody struct {
	QueryId string `json:"query_id"`
	Target string `json:"target"`
}

type KadFindNodeRespBody struct {
	QueryId string `json:"query_id"`
	Closest []json.RawMessage `json:"closest"`
}

type BackfillBody struct {
	Author string `json:"author"`
	From *int64 `json:"from,omitempty"`
}

type PerfMarkBody struct {
	At *int64 `json:"at,omitempty"`
	Note *string `json:"note,omitempty"`
}

type CancelBody struct {
}

type CleanupBody struct {
}

type CurateBody struct {
}

type TendrilResultBody struct {
	CallId *string `json:"callId,omitempty"`
	Output json.RawMessage `json:"output,omitempty"`
}

type TendrilReachBody struct {
	Task *string `json:"task,omitempty"`
	Tools []json.RawMessage `json:"tools,omitempty"`
}

type PetalCellBody struct {
	Cell json.RawMessage `json:"cell,omitempty"`
}

type Envelope struct {
	Chi Chi `json:"chi"`
	Rid string `json:"rid"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
	Sigil *string `json:"sigil,omitempty"`
	Sid *string `json:"sid,omitempty"`
	Wane *uint64 `json:"wane,omitempty"`
	SentAt *int64 `json:"sentAt,omitempty"`
	Dusk *int64 `json:"dusk,omitempty"`
	Ext map[string]map[string]json.RawMessage `json:"ext,omitempty"`
}

// ToneViews maps each chi wire value to its body view type.
var ToneViews = map[Chi]any{
	ChiHello: HelloBody{},
	ChiPrompt: PromptBody{},
	ChiBreath: BreathBody{},
	ChiChunk: ChunkBody{},
	ChiFinish: FinishBody{},
	ChiError: ErrorBody{},
	ChiSessionReady: SessionReadyBody{},
	ChiToolCall: ToolCallBody{},
	ChiToolResult: ToolResultBody{},
	ChiToolInfo: ToolInfoBody{},
	ChiToolMeta: ToolMetaBody{},
	ChiPulse: PulseBody{},
	ChiPermissionAsk: PermissionAskBody{},
	ChiReleasePermit: ReleasePermitBody{},
	ChiEcho: EchoBody{},
	ChiLog: LogBody{},
	ChiDrone: DroneBody{},
	ChiDroneRetrofit: DroneRetrofitBody{},
	ChiPeerAdd: PeerAddBody{},
	ChiPeerRemove: PeerRemoveBody{},
	ChiAttach: AttachBody{},
	ChiDetach: DetachBody{},
	ChiWaneSync: WaneSyncBody{},
	ChiGossipPublish: GossipPublishBody{},
	ChiKadFindNode: KadFindNodeBody{},
	ChiKadFindNodeResp: KadFindNodeRespBody{},
	ChiBackfill: BackfillBody{},
	ChiPerfMark: PerfMarkBody{},
	ChiCancel: CancelBody{},
	ChiCleanup: CleanupBody{},
	ChiCurate: CurateBody{},
	ChiTendrilResult: TendrilResultBody{},
	ChiTendrilReach: TendrilReachBody{},
	ChiPetalCell: PetalCellBody{},
}
